.PHONY: clean
clean:
	@echo nothing to do

.PHONY: usim
usim:
	git clone https://github.com/JNSpears/usim.git


# lwasm from lwtools 4.19 @ http://www.lwtools.ca/releases/lwtools/lwtools-4.19.tar.gz
.PHONY: lwtools
lwtools:
	wget http://www.lwtools.ca/releases/lwtools/lwtools-4.19.tar.gz
	tar -xvzf lwtools-4.19.tar.gz
	make -C lwtools-4.19
